name: 更新 Cloudflare DNS 记录

on:
  schedule:
    - cron: '0 1 * * *'  # 每天零点运行
  workflow_dispatch:

jobs:
  update-cloudflare-record:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版 runner

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装 Python 和依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests jq

      - name: 读取 Fission_ip.txt 中的 IP 地址
        id: read_ip
        run: |
          # 读取 Fission_ip.txt 中的 IP 地址并处理
          IP_ADDRESSES=$(cat Fission_ip.txt | tr '\n' ',')  # 用逗号连接多个 IP 地址
          echo "IP 地址：$IP_ADDRESSES"
          echo "IP_ADDRESSES=$IP_ADDRESSES" >> $GITHUB_ENV  # 设置环境变量

      - name: 清除现有 DNS 记录（保留指定 IP）
        run: |
          # 从 Secrets 中获取 Cloudflare 配置信息
          CF_API_KEY="${{ secrets.CF_API_KEY }}"
          CF_ZONE_ID="${{ secrets.CF_ZONE_ID }}"
          CF_DOMAIN_NAME="${{ secrets.CF_DOMAIN_NAME }}"

          # 设置 API 请求头
          headers="Authorization: Bearer $CF_API_KEY"
          
          # 获取现有 DNS 记录
          dns_records_url="https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/dns_records"
          response=$(curl -s -X GET "$dns_records_url" -H "$headers")
          
          # 获取要删除的记录，保留 IP 地址 74.48.144.51
          record_ids=$(echo "$response" | jq -r '.result[] | select(.name == "'"$CF_DOMAIN_NAME"'") | select(.content != "74.48.144.51") | .id')
          
          # 删除旧的 DNS 记录
          for record_id in $record_ids; do
            curl -s -X DELETE "$dns_records_url/$record_id" -H "$headers"
            echo "Deleted DNS record: $record_id"
          done

      - name: 更新 Cloudflare DNS 记录
        run: |
          # 从 Secrets 中获取 Cloudflare 配置信息
          CF_API_KEY="${{ secrets.CF_API_KEY }}"
          CF_ZONE_ID="${{ secrets.CF_ZONE_ID }}"
          CF_DOMAIN_NAME="${{ secrets.CF_DOMAIN_NAME }}"
          dns_records_url="https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/dns_records"
          
          # 获取从文件读取的 IP 地址
          IP_ADDRESSES="${{ env.IP_ADDRESSES }}"
          
          # 遍历每个 IP 地址并更新 DNS 记录
          for IP in $(echo $IP_ADDRESSES | tr ',' '\n'); do
            # 确保 IP 格式正确，使用正则表达式检查
            if [[ ! $IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Invalid IP address format: $IP. Skipping."
              continue
            fi

            # 使用多行字符串创建新的 DNS 记录
            data="{\"type\": \"A\", \"name\": \"$CF_DOMAIN_NAME\", \"content\": \"$IP\", \"ttl\": 60, \"proxied\": false}"

            response=$(curl -s -X POST "$dns_records_url" -H "Authorization: Bearer $CF_API_KEY" -H "Content-Type: application/json" --data "$data")

            # 检查是否成功
            if [[ $(echo "$response" | jq -r '.success') == "true" ]]; then
              echo "Successfully updated DNS record for $CF_DOMAIN_NAME to $IP"
            else
              echo "Failed to update DNS record for $CF_DOMAIN_NAME to $IP. Response: $response"
            fi
          done
