name: Update Fission IP

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次
  workflow_dispatch:  # 手动触发

jobs:
  update-ip:
    runs-on: ubuntu-latest

    steps:
      # 检出代码库
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 安装 curl 和 xmllint
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl libxml2-utils
          sudo apt-get clean

      # 获取数据并写入文件
      - name: Fetch IP and Update File
        run: |
          URL="https://www.wetest.vip/page/cloudflare/address_v4.html"
          OUTPUT_FILE="Fission_ip.txt"
          echo -n > $OUTPUT_FILE # 清空文件内容

          # 循环提取每一行数据（从 tr[6] 到 tr[8]）
          for i in $(seq 6 8); do
            DATA=$(curl -s "$URL" | xmllint --html --xpath "string(/html/body/div[2]/div[2]/div/div[2]/div[2]/table/tbody/tr[$i]/td[2])" - 2>/dev/null)
            
            # 使用正则表达式来验证是否是有效的 IP 地址
            if echo "$DATA" | grep -Pq '^(\d{1,3}\.){3}\d{1,3}$'; then
              echo "$DATA" >> $OUTPUT_FILE
            fi
          done

      # 提交更改
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # 检查文件是否有更改
          if ! git diff --quiet; then
            git add Fission_ip.txt
            git commit -m "Update Fission_ip.txt with latest IPs"
            git push origin HEAD:main
          else
            echo "No changes detected, skipping commit."
          fi

      # 等待 5 秒
      - name: Wait 5 seconds
        run: sleep 5

      # 触发 bestdns.yaml
      - name: Trigger BestDNS Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: bestdns-update # 自定义事件名称
